import type { Metadata } from 'next';
import './globals.css';

import localFont from 'next/font/local';
import { cn } from '@/lib/utils';

const satoshiFont = localFont({
  src: '../assets/fonts/Satoshi-Variable.ttf',
  variable: '--font-satoshi',
  // declarations: [{ prop: 'font-feature-settings', value: '"ss03" 1' }],
});

const jetBrainsMonoFont = localFont({
  src: '../assets/fonts/JetBrainsMono-Variable.ttf',
  variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(satoshiFont.variable, jetBrainsMonoFont.variable, 'antialiased font-feature-ss03')}>
        {children}
      </body>
    </html>
  );
}
